### PR TITLE
UPDATE:Transfer Function

### PR DESCRIPTION
**Pull request by morelucks**
This pull request introduces the transfer function, enabling the transfer of USDT from one user to another using World ID for identity verification. and the test cases

### CODE REVIEW

**Comment by casweeney** [comment]
@morelucks I think you need to pull from main and sync your implementation with the existing codebase. Good work.

**Comment by morelucks** [comment]
OK thanks

**Comment by Dprof-in-tech** [comment]
@morelucks The code looks good but it seems you did not remove the node modules from the commit history, please do so and also remove the package-lock.json file from the commit history, its an auto generated file.

**Comment by Dprof-in-tech** [comment]
then please you might have to run forge fmt so that the CI/CD workflow can run successfully

**Review by Dprof-in-tech — APPROVED** [review]
chnages approved

**Pull request merged**
